---
- hosts: all
  remote_user: root
  roles:
    - role: 'v2ray'
      vars:
          uuid: '53eb9e88-fcdb-4499-8263-9b2ccb9b1802'
          alterId: 64
          httpsPort: 443
          wsPath: '/ws'
          tlsPort: 8887
          h2Port: 8443
          h2Path: 'h2'
