---
- name: create directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ V2rayRootDir }}"
    - "{{ V2rayConfDir }}"
    - "{{ V2rayBinDir }}"
    - "{{ V2raySslDir }}"

- name: upload v2ray.service
  template:
    src: v2ray.service.j2
    dest: "/etc/systemd/system/v2ray.service"
    owner: root
    group: root
    mode: 0644
  notify:
    - daemon reload

- name: ensure that v2ray is started
  service:
    name: v2ray
    state: started
