---
- name: create directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ V2rayRootDir }}"
    - "{{ V2rayConfDir }}"
    - "{{ V2rayBinDir }}"
    - "{{ V2raySslDir }}"

- name: Copy Binaries
  copy:
    src: {{ item.src }}
    dest: {{ item.dest }}
    owner: root
    group: root
    mode: '0755'
  with_items:
    - { src: "v2ray", dest: "{{V2rayBinDir}}/v2ray"}
    - { src: "v2ctl", dest: "{{V2rayBinDir}}/v2ctl"}

- name: upload v2ray.service
  template:
    src: v2ray.service.j2
    dest: "/etc/systemd/system/v2ray.service"
    owner: root
    group: root
    mode: 0644
  notify:
    - daemon reload

- name: upload v2ray config
  template:
    src: config.json.j2
    dest: "{{ V2rayConfDir}}/config.json"
    owner: root
    group: root
    mode: 0644
  notify:
    - start v2ray

- name: ensure that v2ray is started
  service:
    name: v2ray
    state: started
